import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en" className="scroll-p-32 xl:scroll-p-36">
      <Head>
        {/* Meta tags dynamically generated by metaSEO (https://metaseo.itsvg.in) */}
        <meta charSet="UTF-8" />
        <meta
          name="title"
          content="RTU THAR 2023 | Rajasthan's Biggest Techno-Management Fest"
        />
        <meta
          name="description"
          content="Rajasthan's biggest techno management festival, THAR-23 is a celebration for intellectuals across the country."
        />
        <meta name="copyright" content="TeamTHAR" />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="rtuthar.in" />
        <meta
          property="og:title"
          content="RTU THAR 2023 | Rajasthan's Biggest Techno-Management Fest"
        />
        <meta
          property="og:description"
          content="Rajasthan's biggest techno management festival, THAR-23 is a celebration for intellectuals across the country."
        />
        <meta property="og:image" content="https://rtuthar.in/og.png" />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="rtuthar.in" />
        <meta
          property="twitter:title"
          content="RTU THAR 2023 | Rajasthan's Biggest Techno-Management Fest"
        />
        <meta
          property="twitter:description"
          content="Rajasthan's biggest techno management festival, THAR-23 is a celebration for intellectuals across the country."
        />
        <meta property="twitter:image" content="https://rtuthar.in/og.png" />
        <meta http-equiv="content-language" content="en" />
        <link rel="icon" href="/favicon.png" />
        {/* Google Site Verification */}
        <meta
          name="google-site-verification"
          content="N_jA3DHZLTm0Kk7Wdo6RcaBKCSqyxATyk6oMvTbezvA"
        />
      </Head>
      <body>
        <div className="relative">
          <Main />
          <NextScript />
        </div>
      </body>
    </Html>
  );
}
