import Head from "next/head";
import { NavBar } from "../components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative z-20">
        <NavBar />
        <p className="text-red-600 text-xl">Hello RTU</p><br/>
      </main>
      <div className="h-[100vh] overflow-hidden fixed left-0 top-0 z-[1]">
        <video
          autoPlay
          muted
          loop
          className="w-[100vw] object-fill h-full pointer-events-none scale-110 brightness-[1]"
          id="bg-vid"
          // TODO: test for lazyload and on load complete event
          preload="none"
          onLoadedData={() => console.log(69)}
        >
          <source src="/assets/videos/bg.mp4" type="video/mp4" />
        </video>
      </div>
    </>
  );
}
